openapi: '3.0.0'
info:
  title: 'Express-rest-api'
  version: 1.0.0
paths:
  /api/v1/auth/register:
    post:
      summary: '회원가입'
      tags: [Auth]
      description: '유저 회원가입'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: 'test@gmail.com'
                username:
                  type: string
                  example: '홍길동'
                password:
                  type: string
                  example: 'password'
      responses:
        '201':
          description: 'Created'
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  email:
                    type: string
                    example: 'test@gmail.com'
                  username:
                    type: string
                    example: '홍길동'
                  createdAt:
                    format: datetime
                    example: '2022-03-02T11:59:55.561Z'
                  updatedAt:
                    format: datetime
                    example: '2022-03-02T11:59:55.561Z'
        '400':
          description: 'Schema 에러'
        '409':
          description: 'EXISTED_USER : 이미 유저가 존재할 경우(email, username 기준)'
  /api/v1/auth/login:
    post:
      summary: '로그인'
      tags: [Auth]
      description: '유저 로그인'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: 'test@gmail.com'
                password:
                  type: string
                  example: 'password'
      responses:
        '200':
          description: 'OK'
        '400':
          description: 'Schema 에러'
        '403':
          description: 'Wrong password'
        '404':
          description: 'Not found user'
  /api/v1/auth/logout:
    post:
      summary: '로그아웃'
      tags: [Auth]
      description: '유저 로그아웃'
      responses:
        '200':
          description: 'OK'
